version: '3.2'

volumes:
  db-data:
    driver: local
  ux-dist:
    driver: local
  styles-dist:
    driver: local

services:
  styles:
    build: ./styles
    command: ["gulp", "--cwd=semantic", "build"]
    entrypoint: ["./entrypoint.sh"]
    env_file:
    - ./envfile
    volumes:
    - type: volume
      source: styles-dist
      target: /home/node/dist/
  ux:
    build: ./ux
    command: ["npm", "run", "build"]
    entrypoint: ["./entrypoint.sh"]
    env_file:
    - ./envfile
    volumes:
    - type: volume
      source: ux-dist
      target: /home/node/code/dist/
    - type: volume
      source: styles-dist
      target: /home/node/code/src/styles/
      read_only: true
  db:
    image: postgres:10
    env_file:
    - ./envfile
    volumes:
    - db-data:/var/lib/postgresql/data/
  app:
    build: ./app
    env_file:
    - ./envfile
    links:
    - db
  server:
    build: ./server
    env_file:
    - ./envfile
    links:
    - app