version: '3.2'

services:
  app:
    volumes:
    - ./app:/home/nonroot
  server:
    links:
    - ux
    ports:
    - 8080:80
    - 8081:443
  ux:
    command: ["yarn", "run", "watch"]
    volumes:
    - ./ux:/home/node
  styles:
    command: ["gulp", "--cwd=semantic", "watch"]
    volumes:
    - ./styles:/home/node