version: '3.2'

# ports are not attached to host by default
# you're advised to use a proxy for your container
# see: https://github.com/jwilder/nginx-proxy
# also: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
# also: https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
# also: https://github.com/italomaia/reverse-proxy (all stitched up proxy solution)

secrets:
  flask_secret_key:
    file: ./secrets/flask_secret_key
  postgres_usr:
    file: ./secrets/postgres_usr
  postgres_pwd:
    file: ./secrets/postgres_pwd

services:
  server:
    volumes:
    - type: volume
      source: ux-dist
      target: /usr/share/nginx/html
      read_only: true