version: '3.2'

services:
  app:
    env_file:
    - ./envfile-dev
    volumes:
    - ./app:/home/nonroot
  server:
    command: ["nginx-debug", "-g", "daemon off;"]
    entrypoint: ["./entrypoint.sh"]
    env_file:
    - ./envfile-dev
    links:
    - ux
    ports:
    - 8080:80
    - 8081:443
  ux:
    command: ["npm", "run", "dev"]
    env_file:
    - ./envfile-dev
    volumes:
    - ./ux/build:/home/node/build
    - ./ux/src:/home/node/src
    - ./ux/static:/home/node/static
    - ./ux/test:/home/node/test
  styles:
    command: ["gulp", "--cwd=semantic", "watch"]
    env_file:
    - ./envfile-dev
    volumes:
    - ./styles/semantic:/home/node/semantic
